### ISSUE TITLE
汉化导致的游戏bug

### ISSUE THREAD

**Issue by GrayZ77** [Xzonn/ParanormasightChsLocalization#4]
在游戏开始阶段，汉化后的游戏会在一开始无法进入第一个故事，而是突然退出到一个空白的故事图表，并且没有任何方式能够进入第一个故事，这个bug在讲汉化补丁还原为游戏源文件时消失。

**Comment by GrayZ77** [comment]
目前发现这个bug会在任何进入过场字幕的时候出现，导致游戏无法正常进行下去

**Comment by Xzonn** [comment]
按 [这个视频 01:08](https://www.bilibili.com/video/BV1tM4y1x7nq/?t=68) 处，截一下“生成版本 ID”的图我看一下。

**Comment by Xzonn** [comment]
盗版游戏用补丁有问题的，请自行解决，我只保证正版游戏可以用补丁。
